# Generated by Django 3.1 on 2020-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('evolutions', models.CharField(max_length=100, null=True)),
                ('base_stats', models.JSONField(default=dict, null=True)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
