# Generated by Django 3.1 on 2020-08-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution_chains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
